# Generated by Django 4.1.7 on 2023-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('energy', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('sugar', models.FloatField()),
                ('calcium', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('fa_sat', models.FloatField()),
                ('fa_mono', models.FloatField()),
                ('fa_poly', models.FloatField()),
                ('cholest', models.IntegerField()),
            ],
        ),
    ]
