# Generated by Django 4.1.7 on 2023-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcheck', '0002_alter_diary_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='calcium',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='cholest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='fa_mono',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='fa_poly',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='fa_sat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='potassium',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='protein',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sodium',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sugar',
            field=models.FloatField(null=True),
        ),
    ]
